USE [project]
GO

/****** Object:  Table [dbo].[RELATION]    Script Date: 27-03-2026 13:58:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RELATION](
	[RELATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[RELATION_NAME] [varchar](10) NULL,
PRIMARY KEY CLUSTERED 
(
	[RELATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


