USE [project]
GO

/****** Object:  Table [dbo].[STATE]    Script Date: 27-03-2026 13:58:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[STATE](
	[STATE_ID] [int] IDENTITY(1,1) NOT NULL,
	[STATE_NAME] [varchar](20) NULL,
	[COUNTRY_ID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[STATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[STATE]  WITH CHECK ADD FOREIGN KEY([COUNTRY_ID])
REFERENCES [dbo].[COUNTRY] ([COUNTRY_ID])
GO


