USE [project]
GO

/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 27-03-2026 13:52:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLOYEE](
	[EMP_ID] [int] IDENTITY(1001,1) NOT NULL,
	[FIRST_NAME] [varchar](20) NULL,
	[LAST_NAME] [varchar](20) NULL,
	[EMAIL] [varchar](20) NOT NULL,
	[SALARY] [int] NULL,
	[STATE_ID] [int] NULL,
	[DEPARTMENT_ID] [int] NULL,
	[MANAGER_ID] [int] NULL,
	[DATE_OF_BIRTH] [date] NULL,
	[TODAY_DATE] [datetime] NULL,
	[UPDATED_DATE] [datetime] NULL,
	[CREATED_DATE] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[EMP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[LAST_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EMPLOYEE] ADD  DEFAULT (getdate()) FOR [TODAY_DATE]
GO

ALTER TABLE [dbo].[EMPLOYEE] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([DEPARTMENT_ID])
REFERENCES [dbo].[DEPARTMENT] ([DEPT_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([DEPARTMENT_ID])
REFERENCES [dbo].[DEPARTMENT] ([DEPT_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([DEPARTMENT_ID])
REFERENCES [dbo].[DEPARTMENT] ([DEPT_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([DEPARTMENT_ID])
REFERENCES [dbo].[DEPARTMENT] ([DEPT_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([MANAGER_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([STATE_ID])
REFERENCES [dbo].[STATE] ([STATE_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([STATE_ID])
REFERENCES [dbo].[STATE] ([STATE_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([STATE_ID])
REFERENCES [dbo].[STATE] ([STATE_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD FOREIGN KEY([STATE_ID])
REFERENCES [dbo].[STATE] ([STATE_ID])
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD CHECK  ((datediff(year,[DATE_OF_BIRTH],getdate())>=(18)))
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD CHECK  ((datediff(year,[DATE_OF_BIRTH],getdate())>=(18)))
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD CHECK  ((datediff(year,[DATE_OF_BIRTH],getdate())>=(18)))
GO

ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD CHECK  ((datediff(year,[DATE_OF_BIRTH],getdate())>=(18)))
GO


select*from EMPLOYEE