USE [project]
GO

/****** Object:  UserDefinedFunction [dbo].[FINDOUT_AGE]    Script Date: 27-03-2026 14:01:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE   FUNCTION [dbo].[FINDOUT_AGE] (@DATE_OF_BIRTH DATETIME)
RETURNS INT
AS
BEGIN
DECLARE @AGE AS INT

SELECT @AGE=DATEDIFF(YY,@DATE_OF_BIRTH,GETDATE())
RETURN @AGE
END
GO


