USE [project]
GO

/****** Object:  View [dbo].[GET_ALL_EMPLOYEE_V]    Script Date: 27-03-2026 13:59:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_ALL_EMPLOYEE_V] AS
SELECT
 E.EMP_ID,
 E.FIRST_NAME+' '+E.LAST_NAME AS FULL_NAME,
 E.SALARY,
 E.DATE_OF_BIRTH,
 --E.CREATED_DATE,
 S.STATE_NAME,
 C.COUNTRY_NAME,
 R.REGION_NAME,
 D.DEPT_NAME,
 M.FIRST_NAME+' '+M.LAST_NAME AS MANAGER_NAME
 FROM EMPLOYEE E
 INNER JOIN STATE S ON E.STATE_ID=S.STATE_ID
 INNER JOIN COUNTRY C ON S.COUNTRY_ID=C.COUNTRY_ID
 INNER JOIN REGION R ON C.REGION_ID=R.REGION_ID
 INNER JOIN DEPARTMENT D ON  D.DEPT_ID=E.DEPARTMENT_ID
 INNER JOIN EMPLOYEE M ON M.EMP_ID = E.MANAGER_ID
GO


