USE [project]
GO

/****** Object:  StoredProcedure [dbo].[GET_ALL_EMPLOYEE]    Script Date: 27-03-2026 14:00:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[GET_ALL_EMPLOYEE] 
AS
BEGIN
 SELECT
 E.EMP_ID
 ,E.FIRST_NAME+' '+E.LAST_NAME AS FULL_NAME
 ,E.SALARY
 ,E.EMAIL
 --,(SELECT [FINDOUT_AGE] [@DATE_OF_BIRTH])AS AGE
 ,D.DEPT_NAME
 ,M.FIRST_NAME+' '+M.LAST_NAME AS MANAGER_NAME
 ,CASE WHEN DT.DEPENDENTS_COUNT IS NULL THEN 0 ELSE DT.DEPENDENTS_COUNT END AS DEPENDENTS_COUNT
 ,S.STATE_NAME
 ,C.COUNTRY_NAME
 ,R.REGION_NAME
 ,E.CREATED_DATE
 ,E.UPDATED_DATE
 FROM EMPLOYEE E
 INNER JOIN STATE S ON E.STATE_ID=S.STATE_ID
 INNER JOIN COUNTRY C ON S.COUNTRY_ID=C.COUNTRY_ID
 INNER JOIN REGION R ON C.REGION_ID=R.REGION_ID
 INNER JOIN DEPARTMENT D ON  D.DEPT_ID=E.DEPARTMENT_ID
 INNER JOIN EMPLOYEE M ON M.EMP_ID = E.MANAGER_ID
 LEFT OUTER JOIN #DEPENDENT_TABLE DT ON DT.EMP_ID=E.EMP_ID
END
GO


