USE [project]
GO

/****** Object:  Table [dbo].[DEPENDENT_TABLE]    Script Date: 27-03-2026 13:56:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPENDENT_TABLE](
	[DEPENDENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[FIRST_NAME] [varchar](10) NULL,
	[LAST_NAME] [varchar](10) NULL,
	[RELATION_ID] [int] NULL,
	[PERCENTAGE] [varchar](10) NULL,
	[EMP_ID] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[DEPENDENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([CREATED_BY])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([EMP_ID])
REFERENCES [dbo].[EMPLOYEE] ([EMP_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO

ALTER TABLE [dbo].[DEPENDENT_TABLE]  WITH CHECK ADD FOREIGN KEY([RELATION_ID])
REFERENCES [dbo].[RELATION] ([RELATION_ID])
GO


