USE [project]
GO

/****** Object:  View [dbo].[GET_ALL_EMPLOYEE_VIEW]    Script Date: 27-03-2026 13:59:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[GET_ALL_EMPLOYEE_VIEW] AS
SELECT EMP_ID, FIRST_NAME
FROM EMPLOYEE
GO


